# Generated by Django 3.2.20 on 2024-03-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('situacao', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=255)),
                ('natureza_juridica', models.CharField(max_length=255)),
                ('porte', models.CharField(max_length=255)),
                ('atividade_principal', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=50)),
                ('numero_funcionarios', models.IntegerField()),
                ('faturamento_anual_estimago', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vendedor_responsavel', models.CharField(max_length=255)),
            ],
        ),
    ]
