# Generated by Django 3.2.25 on 2024-03-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='faturamento_anual_estimago',
            new_name='faturamento_anual_estimado',
        ),
    ]
